### ISSUE TITLE
search_elastic\guzzle_exception does not fully implement \GuzzleHttp\Psr7\Response

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-search_elastic#117]
Occasionally indexing fails with the following error.

```
Processing area: Lightboxgallery - activity information
No new documents to index.
Processing area: Open Forum - posts
... used 8549 dbqueries
... used 230.76592087746 seconds
Scheduled task failed: Global search indexing (core\task\search_index_task),Call to undefined method search_elastic\guzzle_exception::getBody()
```

**Comment by MURBASLMS** [comment]
full stack trace, doesn't happen all the time and i can't see why it does exactly:

Execute scheduled task: Global search indexing (core\task\search_index_task)
... started 15:30:02. Current memory use 27.9MB.
Processing area: HTML block content
  No new documents to index.
Processing area: Peer work - activity information
  No new documents to index.
Processing area: Open Forum - posts
  No new documents to index.
Processing area: IMS content package - resource information
  No new documents to index.
Processing area: Lightboxgallery - activity information
  No new documents to index.
Processing area: OU blog - activity information
  No new documents to index.
Processing area: OU blog - posts comments
  No new documents to index.
Processing area: OUWiki - activity information
  No new documents to index.
Processing area: OUWiki - page versions
  No new documents to index.
Processing area: Questionnaire - activity information
  No new documents to index.
Processing area: Glossary - activity information
  No new documents to index.
Processing area: Questionnaire - questions
  No new documents to index.
Processing area: Quiz - activity information
  No new documents to index.
Processing area: SCORM package - activity information
  No new documents to index.
Processing area: Survey - activity information
  No new documents to index.
Processing area: URL
  No new documents to index.
Processing area: Wiki - activity information
  No new documents to index.
Processing area: Wiki - collaborative pages
  No new documents to index.
Processing area: H5P - activity information
  No new documents to index.
Processing area: Workshop - activity information
  No new documents to index.
Processing area: Choice - activity information
  No new documents to index.
Processing area: Database - activity information
  No new documents to index.
Processing area: Course custom fields
  No new documents to index.
Processing area: Assignment - activity information
  No new documents to index.
Processing area: Attendance - activity information
  No new documents to index.
Processing area: Feedback - activity information
  No new documents to index.
Processing area: Facetoface activities
  No new documents to index.
Processing area: Chat - activity information
  No new documents to index.
Processing area: Database - entries
  No new documents to index.
Processing area: Custom certificate - activity information
  No new documents to index.
Processing area: Book - chapters
  No new documents to index.
Processing area: Forum - posts
... used 11984 dbqueries
... used 431.07597184181 seconds
Scheduled task failed: Global search indexing (core\task\search_index_task),Call to undefined method search_elastic\guzzle_exception::getBody()
Backtrace:
* line 198 of /search/engine/elastic/classes/engine.php: call to search_elastic\engine->get_es_version_details()
* line 452 of /search/engine/elastic/classes/engine.php: call to search_elastic\engine->get_es_lucene_version()
* line 576 of /search/engine/elastic/classes/engine.php: call to search_elastic\engine->create_payload()
* line 1187 of /search/classes/manager.php: call to search_elastic\engine->add_documents()
* line 59 of /lib/classes/task/search_index_task.php: call to core_search\manager->index()
* line 257 of /lib/cronlib.php: call to core\task\search_index_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

**Comment by cameron1729** [comment]
The main problem here is that es_request::get is always supposed to return a PSR-7 response object, but when you look at esrequest::http_action - it does this:

```
    private function http_action($psr7request) {
        try {
            $response = $this->client->send($psr7request);
        } catch (\GuzzleHttp\Exception\BadResponseException $e) {
            $response = $e->getResponse();
        } catch (\GuzzleHttp\Exception\GuzzleException $e) {
            // This case does not provide a response object with a consistent interface so we need to make one.
            $response = new \search_elastic\guzzle_exception();
        }

        return $response;
    }
    ```
    
 \search_elastic\guzzle_exception does not implement a valid PSR-7 response, as it only implements the `getStatusCode` method. This is fine for the case where the plugin attempts to check if elastic search is set up correctly, because all it does is check the status code. But other parts of the code need `getBody` to be implemented.

`GuzzleException` (which is the exception that leads to `guzzle_exception` ultimately being thrown) gets thrown when a request to a URL that doesn't resolve is made. To me, this implies what's happening is that the elastic search server is somehow becoming unavailable mid-indexing. Replication steps below:

1. Hack `classes/engine.php` so that `is_server_ready`  always returns true:
```
    public function is_server_ready($stack = false) {
        return true;
        ```
2. Make sure the elasticsearch service is stopped: `service elasticsearch stop`
3. Run the task ` php admin/cli/scheduled_task.php --execute="\\core\\task\\search_index_task"`

In this situation, we simulate a situation where the ready check passes, but then elastic search is unavailable, and Guzzle's requests fail.

**Comment by cameron1729** [comment]
Looking closer, I feel like we shouldn't be eating these exceptions. Most places in code simply call `esclient::post` expecting the data that comes back to be valid. So we could:

1. Add more error handling in all those places
2. Just allow exceptions to surface (relevant errors will be in the exception anyway)

It's not clear to me why there's a need to eat the exception and return the message in a response object. So my vote is to simply let the exceptions surface themselves.
