### ISSUE TITLE
local_aws dependency in Moodle 4.4+

### ISSUE THREAD

**Issue by tuanngocnguyen** [catalyst/moodle-search_elastic#130]
Hi @mattporritt ,

Hope you are doing well.

Since AWS sdk was added to Moodle, the local_aws seems to be redundant.

Do you have any plan to remove the dependency, or we still need to keep it?

Regards
Nathan

**Comment by mattporritt** [comment]
Hi @tuanngocnguyen ,
As mentioned in the related this dependency has been removed for Moodle LMS version 4.4 and above. Using the MOODLE_404_STABLE branch

Cheers,
Matt P
