### ISSUE TITLE
Search keyword is order dependant

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-search_elastic#14]
eg searching for "dentist lithograph" shows a result, but searching for "lithograph dentist" doesn't find the same result. Further more searching for  "lithograph OR dentist" doesn't return anything either.

https://s-cqu-mba.catalyst-au.net/search/?page=0&q=dentist%20lithograph&title&timestart=0&timeend=0

**Comment by mattporritt** [comment]
Have confirmed this as an issue, thanks for reporting it. 
I'll start on the fix in the next couple of days

**Comment by mattporritt** [comment]
So this is an issue with query VS query_string in the search params that get passed to Elasticsearch.
The first step here is to write some tests to cover basic search scenarios, something which I should have done a long time ago. I think this is a regression when I was fixing another issue.

I may also need to drop support for Elasticsearch 2.3, but I don't think that will be a big deal

**Comment by mattporritt** [comment]
I've created branch: issue14-searchorder that contains tests and initial fix for issue.
I just need to write a bunch more tests covering different search permutations and make sure they all continue to pass

**Comment by mattporritt** [comment]
closing this off, laster version on master fixes this issue
