### ISSUE TITLE
Requirement for local_aws on a local ElasticSearch instance?

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-search_elastic#21]
Hi,

I am currently looking into search_elastic to run it as an alternativ to search_solr, mainly because Elasticsearch seems to be easier to install and run on our RHEL 7 systems.

I have seen that search_elastic requires local_aws. May I ask if local_aws is really necessary for local ElasticSearch instances (i.e. not in AWS)?

If it is really necessary, could you please also publish local_aws to the Moodle plugins repository so that we can install it from there and get update notifications?

If it is not necessary, could you please remove this requirement from version.php and e.g. replace it with some custom checks if local_aws is installed before a AWS instance can be configured?

Thanks,
Alex

**Comment by mattporritt** [comment]
Even if you are not using an AWS elasticsearch instance the plugin local/aws is still a requirement. This plugin relies on the Guzzle library to make all its POST and GET calls. Guzzle is supplied by local/aws. 

There are plans to add local/aws to the plugin dir. However it does take time for the adding and approval process for a plugin. the avg approval time for a plugin in the plugin dir can be found here: https://moodle.org/plugins/queue.php

**Comment by abias** [comment]
> Even if you are not using an AWS elasticsearch instance the plugin local/aws is still a requirement. This plugin relies on the Guzzle library to make all its POST and GET calls. Guzzle is supplied by local/aws.

Thanks, Matt, for this feedback.

> There are plans to add local/aws to the plugin dir. However it does take time for the adding and approval process for a plugin. the avg approval time for a plugin in the plugin dir can be found here: https://moodle.org/plugins/queue.php

I am aware that the approval takes time, I have published 10+ plugins myself in the plugin dir.
But you have to make the first step and add it there ;)
Good to hear that you are considering this step, thanks.
