### ISSUE TITLE
course filter is not working either

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-search_elastic#3]
![image](https://cloud.githubusercontent.com/assets/187449/22277384/271c3138-e30f-11e6-927b-48360274e9b1.png)

![image](https://cloud.githubusercontent.com/assets/187449/22277390/31cfe1e2-e30f-11e6-86b8-de62d62219c0.png)

**Comment by mattporritt** [comment]
https://github.com/catalyst/moodle-search_elastic/commit/820d14238a6fc69952abdc42eb49416d53722b52 fixes this issue.
Can you confirm?

**Comment by brendanheywood** [comment]
Nope: 
![image](https://cloud.githubusercontent.com/assets/187449/22277759/33bc20d0-e312-11e6-9691-baa65848af74.png)

**Comment by mattporritt** [comment]
Current build of master should fix this

**Comment by brendanheywood** [comment]
:+1:
