### ISSUE TITLE
Enable file indexing retroactively is not possible

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-search_elastic#30]
Steps to reproduce:
* Don't enable the "Enable file indexing" setting in search_elastic
* Fully index your Moodle instance
* Enable the "Enable file indexing" setting in search_elastic retroactively

Expected result:
* Moodle / search_elastic will index the existing files additionally to the existing content

Actual result:
* There isn't anything indexed additionally

I assume that this additional index can't be made automatically under the hood and that it basically needs a full re-index of the existing content to also index the existing files. That's why I would just propose to add this fact to the description of the "Enable file indexing" setting in search_elastic.

**Comment by mattporritt** [comment]
Hi Alex,
I will have a look at the code later today. However, I'm almost 100% sure, the issue is the existing documents haven't changed. So even with file indexing on the already indexed content won't be added.
Hopefully this should not be to hard to fix. I will let you know after I look at the code and I have an approach.
I think the core Solr plugin will also have this issue, I'll also check that

Matt P

**Comment by mattporritt** [comment]
I've now confirmed the issue and it is because the existing parent documents haven't changed.
I will double check that this also occurs with the solr plugin and if it does I'll lodge a tracker issue to fix this in core.

It does look like a core bug to me, but I will confirm

**Comment by mattporritt** [comment]
Hi @abias 
I've confirmed that this issue exists in both the core Solr plugin and the Elasticsearch plugin. A quick look at the code makes me think that this issue lie in the core search API, but I would need to confirm this.

I will raise a core tracker for this.

**Comment by mattporritt** [comment]
Tracker related: https://tracker.moodle.org/browse/MDL-60360

**Comment by mattporritt** [comment]
latest push to master fixes this
