### ISSUE TITLE
Problems with setup on Moodle 3.4

### ISSUE THREAD

**Issue by neeesn** [catalyst/moodle-search_elastic#35]
There is an error in the setup in  Moodle 3.4 and 3.5 where the plugin returns "Section Error" and we cna get no further in the installation. ( we down graded and the plugin and it worked fine) 

![to3dmoq](https://user-images.githubusercontent.com/1931926/45356542-cb5e3880-b5c3-11e8-9936-429c6523c61f.png)

And this is the error:
![5ref1a6](https://user-images.githubusercontent.com/1931926/45356641-14ae8800-b5c4-11e8-805b-0b5088728b82.png)

**Comment by mattporritt** [comment]
This is actually a core Moodle bug, the tracker for it is: https://tracker.moodle.org/browse/MDL-62537 the same thing happens for the core simple search that is now in Moodle. 
As a work around once you have chosen Elastic as the search engine you can access the settings via the search section of the site admin menu or going to (your equivalent of): http://moodle.local/admin/category.php?category=search_elastic

Cheers,
Matt P

**Comment by dmitriim** [comment]
@neeesn  Thanks again for reporting this issue.
We have just updated the plugin directory with a new version of the plugin which has a fix for this issue. Please make sure that you are using the latest code.

Cheers,
Dmitrii
