### ISSUE TITLE
Support for Moodle 3.5

### ISSUE THREAD

**Issue by mglumac** [catalyst/moodle-search_elastic#36]
One issue in classes/query.php, line 321:
For example, this code is never executed because it seams that $usercontents is an object in 3.5 and not an array
`        // Add contexts.
        if (gettype($usercontexts) == 'array') {
            $contexts = $this->construct_contexts($usercontexts);
            array_push ($query['query']['bool']['filter']['bool']['must'], $contexts);
        }
`
Option "Search within enrolled courses only" does not have any effect than

Another change I had to make to make it work is this (added groupid, line 118):
`
        $excludedfields = array('itemid',
                'areaid',
                'courseid',
                'contextid',
                'userid',
                'owneruserid',
                'modified',
                'type',
                'groupid' // added group id, otherwise it always fails when searching for string
        );
`

**Comment by mglumac** [comment]
[patch.txt](https://github.com/catalyst/moodle-search_elastic/files/2473190/patch.txt)

**Comment by dmitriim** [comment]
Hi @mglumac 

Thank you for reporting these issues. I can confirm the first issues. Good catch.

Not sure if I understand what is wrong with groupid? Could you please provide more information? What error did you get? How to replicate it? 

Thanks,
Dmitrii

**Comment by mattporritt** [comment]
Closing this, the OP first issue was patched.
It has been 6 months and no further reports of second issue or additional information being supplied.

**Comment by mattporritt** [comment]
I finally have been able to replicate the groupid issue. I need to confirm if the suggested fix is the best way to go about it.
Either way I will fix this ASAP

**Comment by mattporritt** [comment]
Closing this. Latest release has fix
