### ISSUE TITLE
Error retrieving core_message-message_sent

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-search_elastic#4]
Running CLI reindex command 
sudo -u www-data php search/cli/indexer.php --force --reindex

I'm getting 

Processing Messages - sent area
++ Error retrieving core_message-message_sent 80 document, not all required data is available: Invalid user ++
* line 59 of /message/classes/search/base_message.php: call to debugging()
* line 61 of /message/classes/search/message_sent.php: call to core_message\search\base_message->get_document()
* line ? of unknownfile: call to core_message\search\message_sent->get_document()
* line 103 of /lib/classes/dml/recordset_walk.php: call to call_user_func()
* line 573 of /search/classes/manager.php: call to core\dml\recordset_walk->current()
* line 79 of /search/cli/indexer.php: call to core_search\manager->index()
No new documents to index for Messages - sent area.

Maybe it's been related to some user being removed. Not sure if it needs any attention, but log it as part of my testing.

**Comment by mattporritt** [comment]
Could not reproduce this one, looks to be an issue with the test site being used.
Will close for now can always revisit if it re-appears
