### ISSUE TITLE
Add timeout for requests

### ISSUE THREAD

**Issue by marcusboon** [catalyst/moodle-search_elastic#46]
I have run into a situation where a restored config from another environment results in Moodle upgrade hanging at the search_elastic step as it tries and fails to reach the elastisearch server. Having a configurable timeout would resolve this issue where the elastisearch server falls over and/or cannot be reached.

**Comment by dmitriim** [comment]
With the addition of a health check on the setting page as part of https://github.com/catalyst/moodle-search_elastic/commit/3db6097bd409b91c138d8a5f8594bd568794d1c7#diff-4092c491c25e7e19aceafbe3c49d234ce7d1eca769519197d2ccba7bde75a27e This becomes critical as potentially can break whole site,
