### ISSUE TITLE
general feedback

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-search_elastic#8]
* [ ] $item->index->status >= 300 would be future proof

* [ ] add protection from network failure around json_decode and  $client->post ( $docurl, $payload )->getBody

**Comment by mattporritt** [comment]
Hi Brendan,
I've just updated master with the latest code (I haven't updated plugin directory yet).
It's a fairly large refactor and also now supports batch document processing. The batch processing won't land until Moodle 3.4 (https://tracker.moodle.org/browse/MDL-58654). The plugin is backwards compatible until then, but won't batch process.

It should also be more resilient to the states you've mentioned

Matt P

**Comment by martindCatalyst** [comment]
#11 Typo fix PR
