### ISSUE TITLE
Test support for 4.1 -> Some issues found

### ISSUE THREAD

**Issue by marxjohnson** [catalyst/moodle-search_elastic#89]
I have tested installation, automated tests, and basic indexing/searching on Moodle 4.1. I found the following minor issues:

* Unit tests need renaming and namespacing to match current conventions.
* Some tests use assertions which are deprecated in newer versions of PHPUnit.
* Tests for proxy configuration fail if a proxy is configured for the development environment.

**Comment by dmitriim** [comment]
hey! @marxjohnson have you seen something like following error while working on  the plugin for 4.1? 
```

1) search_elastic_esrequest_testcase::test_get
Error: Class 'GuzzleHttp\Middleware' not found

/var/www/catalyst-moodle/search/engine/elastic/tests/esrequest_test.php:60
/var/www/catalyst-moodle/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/catalyst-moodle/vendor/phpunit/phpunit/phpunit:97
```
getting this in our CI for 4.1 upstream branch...

**Comment by dmitriim** [comment]
By the way the error is gone on the branch from https://github.com/catalyst/moodle-search_elastic/pull/90

**Comment by marxjohnson** [comment]
Yes, I saw that in a few places during my 4.1 testing. I think it's to do with the namespacing (or lack of) in test classes meaning it's not finding the Guzzle class, so I think my changes fixed that.
